// Curated word list for the Arrivals "Code of the Day" feature.
//
// The Lambda picks one of these at random each day in place of the
// previous third-party random-word API. Edit the list here to refresh
// the pool — no schema or resolver changes needed.

const CODE_WORDS = [
  'Anagkazo',
  'Abraham if',
  'Allos',
  'Amplify',
  'Anointed',
  'Anointing',
  'Assistance',
  'Attempt Great Things',
  'Bearing Fruit',
  'Beauty',
  'Blessed',
  'Blood Power',
  'Born Again',
  'Burden',
  'Christians',
  'Church',
  'Communion',
  'Cross',
  'Dangers',
  'Destiny',
  'Detect',
  'Determinants',
  'Develop',
  'Devoted',
  'Double',
  'Duality',
  'Dying',
  'Effective',
  'Engage',
  'Essentials',
  'Evangelism',
  'Excellence',
  'Faith',
  'Fathers',
  'Fellowship',
  'Flow',
  'Following',
  'Forgiveness',
  'Formula',
  'Foundation',
  'Full',
  'Good',
  'Good General',
  'Gospel',
  'Governments',
  'Great',
  'Growth',
  'Hath',
  'Healing',
  'Hearing',
  'Honour',
  'Humility',
  'Influences',
  'Invisible',
  'Laikos',
  'Laws',
  'Leadership',
  'Losing',
  'Loyalty',
  'Make It',
  'Manifestations',
  'Marriage',
  'Mega',
  'Members',
  'Ministerial',
  'Ministry',
  'Miracles',
  'Missionary',
  'Missions',
  'Model',
  'Neutralize',
  'Opportunities',
  'Others',
  'Overcome',
  'Participation',
  'Pastor',
  'Pastoral',
  'Planting',
  'Power',
  'Prayer',
  'Preach',
  'Preparation',
  'Presence',
  'Proof',
  'Prosperity',
  'Proton',
  'Quiet',
  'Recognize',
  'Remembrance',
  'Rules',
  'Sacrificing',
  'Salvation',
  'Secret',
  'Secrets',
  'Serve',
  'Sharing',
  'Shepherding',
  'Signs',
  'Skills',
  'Spiritual',
  'Stages',
  'Start',
  'Staying',
  'Steps',
  'Strong',
  'Subtle',
  'Success',
  'Suffering',
  'Sweet',
  'Teaching',
  'Test',
  'Tithing',
  'Transform',
  'Tree',
  'Unbeatable',
  'Understanding',
  'Victory',
  'Warfare',
  'Wisdom',
  'Wise',
  'Wonders',
  'Work',
  'Greater',
  'Better',
  'Mountains',
]

module.exports = { CODE_WORDS }
